// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: payroll/v1/payroll.proto

package payrollv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPayrollRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayrollId string `protobuf:"bytes,1,opt,name=payroll_id,json=payrollId,proto3" json:"payroll_id,omitempty"`
	TenantId  string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Payday    string `protobuf:"bytes,3,opt,name=payday,proto3" json:"payday,omitempty"`
}

func (x *AddPayrollRequest) Reset() {
	*x = AddPayrollRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payroll_v1_payroll_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPayrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPayrollRequest) ProtoMessage() {}

func (x *AddPayrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payroll_v1_payroll_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPayrollRequest.ProtoReflect.Descriptor instead.
func (*AddPayrollRequest) Descriptor() ([]byte, []int) {
	return file_payroll_v1_payroll_proto_rawDescGZIP(), []int{0}
}

func (x *AddPayrollRequest) GetPayrollId() string {
	if x != nil {
		return x.PayrollId
	}
	return ""
}

func (x *AddPayrollRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AddPayrollRequest) GetPayday() string {
	if x != nil {
		return x.Payday
	}
	return ""
}

type AddPayrollResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayrollId string `protobuf:"bytes,1,opt,name=payroll_id,json=payrollId,proto3" json:"payroll_id,omitempty"`
}

func (x *AddPayrollResponse) Reset() {
	*x = AddPayrollResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payroll_v1_payroll_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPayrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPayrollResponse) ProtoMessage() {}

func (x *AddPayrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payroll_v1_payroll_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPayrollResponse.ProtoReflect.Descriptor instead.
func (*AddPayrollResponse) Descriptor() ([]byte, []int) {
	return file_payroll_v1_payroll_proto_rawDescGZIP(), []int{1}
}

func (x *AddPayrollResponse) GetPayrollId() string {
	if x != nil {
		return x.PayrollId
	}
	return ""
}

type AddPayslipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayrollId string `protobuf:"bytes,1,opt,name=payroll_id,json=payrollId,proto3" json:"payroll_id,omitempty"`
	GrossPay  int32  `protobuf:"varint,4,opt,name=gross_pay,json=grossPay,proto3" json:"gross_pay,omitempty"`
	Tax       int32  `protobuf:"varint,5,opt,name=tax,proto3" json:"tax,omitempty"`
}

func (x *AddPayslipRequest) Reset() {
	*x = AddPayslipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payroll_v1_payroll_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPayslipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPayslipRequest) ProtoMessage() {}

func (x *AddPayslipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payroll_v1_payroll_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPayslipRequest.ProtoReflect.Descriptor instead.
func (*AddPayslipRequest) Descriptor() ([]byte, []int) {
	return file_payroll_v1_payroll_proto_rawDescGZIP(), []int{2}
}

func (x *AddPayslipRequest) GetPayrollId() string {
	if x != nil {
		return x.PayrollId
	}
	return ""
}

func (x *AddPayslipRequest) GetGrossPay() int32 {
	if x != nil {
		return x.GrossPay
	}
	return 0
}

func (x *AddPayslipRequest) GetTax() int32 {
	if x != nil {
		return x.Tax
	}
	return 0
}

type AddPayslipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayslipId string `protobuf:"bytes,1,opt,name=payslip_id,json=payslipId,proto3" json:"payslip_id,omitempty"`
}

func (x *AddPayslipResponse) Reset() {
	*x = AddPayslipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payroll_v1_payroll_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPayslipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPayslipResponse) ProtoMessage() {}

func (x *AddPayslipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payroll_v1_payroll_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPayslipResponse.ProtoReflect.Descriptor instead.
func (*AddPayslipResponse) Descriptor() ([]byte, []int) {
	return file_payroll_v1_payroll_proto_rawDescGZIP(), []int{3}
}

func (x *AddPayslipResponse) GetPayslipId() string {
	if x != nil {
		return x.PayslipId
	}
	return ""
}

type GetPayrollRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayrollId string `protobuf:"bytes,1,opt,name=payroll_id,json=payrollId,proto3" json:"payroll_id,omitempty"`
}

func (x *GetPayrollRequest) Reset() {
	*x = GetPayrollRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payroll_v1_payroll_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPayrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayrollRequest) ProtoMessage() {}

func (x *GetPayrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payroll_v1_payroll_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayrollRequest.ProtoReflect.Descriptor instead.
func (*GetPayrollRequest) Descriptor() ([]byte, []int) {
	return file_payroll_v1_payroll_proto_rawDescGZIP(), []int{4}
}

func (x *GetPayrollRequest) GetPayrollId() string {
	if x != nil {
		return x.PayrollId
	}
	return ""
}

type GetPayrollResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payroll  *Payroll   `protobuf:"bytes,1,opt,name=payroll,proto3" json:"payroll,omitempty"`
	Payslips []*Payslip `protobuf:"bytes,2,rep,name=payslips,proto3" json:"payslips,omitempty"`
}

func (x *GetPayrollResponse) Reset() {
	*x = GetPayrollResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payroll_v1_payroll_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPayrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayrollResponse) ProtoMessage() {}

func (x *GetPayrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payroll_v1_payroll_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayrollResponse.ProtoReflect.Descriptor instead.
func (*GetPayrollResponse) Descriptor() ([]byte, []int) {
	return file_payroll_v1_payroll_proto_rawDescGZIP(), []int{5}
}

func (x *GetPayrollResponse) GetPayroll() *Payroll {
	if x != nil {
		return x.Payroll
	}
	return nil
}

func (x *GetPayrollResponse) GetPayslips() []*Payslip {
	if x != nil {
		return x.Payslips
	}
	return nil
}

type Payroll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Payday   string `protobuf:"bytes,3,opt,name=payday,proto3" json:"payday,omitempty"`
}

func (x *Payroll) Reset() {
	*x = Payroll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payroll_v1_payroll_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payroll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payroll) ProtoMessage() {}

func (x *Payroll) ProtoReflect() protoreflect.Message {
	mi := &file_payroll_v1_payroll_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payroll.ProtoReflect.Descriptor instead.
func (*Payroll) Descriptor() ([]byte, []int) {
	return file_payroll_v1_payroll_proto_rawDescGZIP(), []int{6}
}

func (x *Payroll) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payroll) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Payroll) GetPayday() string {
	if x != nil {
		return x.Payday
	}
	return ""
}

type Payslip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId  string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PayrollId string `protobuf:"bytes,3,opt,name=payroll_id,json=payrollId,proto3" json:"payroll_id,omitempty"`
	GrossPay  int32  `protobuf:"varint,4,opt,name=gross_pay,json=grossPay,proto3" json:"gross_pay,omitempty"`
	Tax       int32  `protobuf:"varint,5,opt,name=tax,proto3" json:"tax,omitempty"`
	NetPay    int32  `protobuf:"varint,6,opt,name=net_pay,json=netPay,proto3" json:"net_pay,omitempty"`
}

func (x *Payslip) Reset() {
	*x = Payslip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payroll_v1_payroll_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payslip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payslip) ProtoMessage() {}

func (x *Payslip) ProtoReflect() protoreflect.Message {
	mi := &file_payroll_v1_payroll_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payslip.ProtoReflect.Descriptor instead.
func (*Payslip) Descriptor() ([]byte, []int) {
	return file_payroll_v1_payroll_proto_rawDescGZIP(), []int{7}
}

func (x *Payslip) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payslip) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Payslip) GetPayrollId() string {
	if x != nil {
		return x.PayrollId
	}
	return ""
}

func (x *Payslip) GetGrossPay() int32 {
	if x != nil {
		return x.GrossPay
	}
	return 0
}

func (x *Payslip) GetTax() int32 {
	if x != nil {
		return x.Tax
	}
	return 0
}

func (x *Payslip) GetNetPay() int32 {
	if x != nil {
		return x.NetPay
	}
	return 0
}

var File_payroll_v1_payroll_proto protoreflect.FileDescriptor

var file_payroll_v1_payroll_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x79,
	0x72, 0x6f, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x61, 0x79, 0x72,
	0x6f, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x22, 0x67, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x50, 0x61, 0x79,
	0x72, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x79, 0x64, 0x61,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x79, 0x64, 0x61, 0x79, 0x22,
	0x33, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x50, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x79, 0x72, 0x6f,
	0x6c, 0x6c, 0x49, 0x64, 0x22, 0x61, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x50, 0x61, 0x79, 0x73, 0x6c,
	0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x79,
	0x72, 0x6f, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x73,
	0x73, 0x5f, 0x70, 0x61, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x67, 0x72, 0x6f,
	0x73, 0x73, 0x50, 0x61, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x78, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x74, 0x61, 0x78, 0x22, 0x33, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x50, 0x61,
	0x79, 0x73, 0x6c, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x61, 0x79, 0x73, 0x6c, 0x69, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x61, 0x79, 0x73, 0x6c, 0x69, 0x70, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x50, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x49, 0x64,
	0x22, 0x74, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x72, 0x6f, 0x6c,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x61, 0x79, 0x72, 0x6f, 0x6c,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x52, 0x07, 0x70, 0x61,
	0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x12, 0x2f, 0x0a, 0x08, 0x70, 0x61, 0x79, 0x73, 0x6c, 0x69, 0x70,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x61, 0x79, 0x72, 0x6f, 0x6c,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x79, 0x73, 0x6c, 0x69, 0x70, 0x52, 0x08, 0x70, 0x61,
	0x79, 0x73, 0x6c, 0x69, 0x70, 0x73, 0x22, 0x4e, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x72, 0x6f, 0x6c,
	0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x61, 0x79, 0x64, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x61, 0x79, 0x64, 0x61, 0x79, 0x22, 0x9d, 0x01, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x73, 0x6c,
	0x69, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x67, 0x72, 0x6f, 0x73, 0x73, 0x5f, 0x70, 0x61, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x67, 0x72, 0x6f, 0x73, 0x73, 0x50, 0x61, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x61, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x61, 0x78, 0x12, 0x17, 0x0a,
	0x07, 0x6e, 0x65, 0x74, 0x5f, 0x70, 0x61, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x6e, 0x65, 0x74, 0x50, 0x61, 0x79, 0x32, 0xf7, 0x01, 0x0a, 0x0e, 0x50, 0x61, 0x79, 0x72, 0x6f,
	0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0a, 0x41, 0x64, 0x64,
	0x50, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x12, 0x1d, 0x2e, 0x70, 0x61, 0x79, 0x72, 0x6f, 0x6c,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x50, 0x61, 0x79,
	0x73, 0x6c, 0x69, 0x70, 0x12, 0x1d, 0x2e, 0x70, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x61, 0x79, 0x73, 0x6c, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x64, 0x64, 0x50, 0x61, 0x79, 0x73, 0x6c, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x61, 0x79, 0x72, 0x6f, 0x6c,
	0x6c, 0x12, 0x1d, 0x2e, 0x70, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x70, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x50, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0xc0, 0x01, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c,
	0x2e, 0x76, 0x31, 0x42, 0x0c, 0x50, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x57, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x6e, 0x74, 0x6f, 0x73, 0x64, 0x61, 0x6e, 0x69, 0x65, 0x6c, 0x2f, 0x67, 0x6f, 0x2d, 0x70,
	0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x2d, 0x63, 0x6f, 0x64, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x2f,
	0x76, 0x31, 0x3b, 0x70, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x50,
	0x58, 0x58, 0xaa, 0x02, 0x0a, 0x50, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x2e, 0x56, 0x31, 0xca,
	0x02, 0x0a, 0x50, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x16, 0x50,
	0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0b, 0x50, 0x61, 0x79, 0x72, 0x6f, 0x6c, 0x6c, 0x3a,
	0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_payroll_v1_payroll_proto_rawDescOnce sync.Once
	file_payroll_v1_payroll_proto_rawDescData = file_payroll_v1_payroll_proto_rawDesc
)

func file_payroll_v1_payroll_proto_rawDescGZIP() []byte {
	file_payroll_v1_payroll_proto_rawDescOnce.Do(func() {
		file_payroll_v1_payroll_proto_rawDescData = protoimpl.X.CompressGZIP(file_payroll_v1_payroll_proto_rawDescData)
	})
	return file_payroll_v1_payroll_proto_rawDescData
}

var file_payroll_v1_payroll_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_payroll_v1_payroll_proto_goTypes = []interface{}{
	(*AddPayrollRequest)(nil),  // 0: payroll.v1.AddPayrollRequest
	(*AddPayrollResponse)(nil), // 1: payroll.v1.AddPayrollResponse
	(*AddPayslipRequest)(nil),  // 2: payroll.v1.AddPayslipRequest
	(*AddPayslipResponse)(nil), // 3: payroll.v1.AddPayslipResponse
	(*GetPayrollRequest)(nil),  // 4: payroll.v1.GetPayrollRequest
	(*GetPayrollResponse)(nil), // 5: payroll.v1.GetPayrollResponse
	(*Payroll)(nil),            // 6: payroll.v1.Payroll
	(*Payslip)(nil),            // 7: payroll.v1.Payslip
}
var file_payroll_v1_payroll_proto_depIdxs = []int32{
	6, // 0: payroll.v1.GetPayrollResponse.payroll:type_name -> payroll.v1.Payroll
	7, // 1: payroll.v1.GetPayrollResponse.payslips:type_name -> payroll.v1.Payslip
	0, // 2: payroll.v1.PayrollService.AddPayroll:input_type -> payroll.v1.AddPayrollRequest
	2, // 3: payroll.v1.PayrollService.AddPayslip:input_type -> payroll.v1.AddPayslipRequest
	4, // 4: payroll.v1.PayrollService.GetPayroll:input_type -> payroll.v1.GetPayrollRequest
	1, // 5: payroll.v1.PayrollService.AddPayroll:output_type -> payroll.v1.AddPayrollResponse
	3, // 6: payroll.v1.PayrollService.AddPayslip:output_type -> payroll.v1.AddPayslipResponse
	5, // 7: payroll.v1.PayrollService.GetPayroll:output_type -> payroll.v1.GetPayrollResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_payroll_v1_payroll_proto_init() }
func file_payroll_v1_payroll_proto_init() {
	if File_payroll_v1_payroll_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_payroll_v1_payroll_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPayrollRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payroll_v1_payroll_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPayrollResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payroll_v1_payroll_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPayslipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payroll_v1_payroll_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPayslipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payroll_v1_payroll_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPayrollRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payroll_v1_payroll_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPayrollResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payroll_v1_payroll_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payroll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payroll_v1_payroll_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payslip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_payroll_v1_payroll_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payroll_v1_payroll_proto_goTypes,
		DependencyIndexes: file_payroll_v1_payroll_proto_depIdxs,
		MessageInfos:      file_payroll_v1_payroll_proto_msgTypes,
	}.Build()
	File_payroll_v1_payroll_proto = out.File
	file_payroll_v1_payroll_proto_rawDesc = nil
	file_payroll_v1_payroll_proto_goTypes = nil
	file_payroll_v1_payroll_proto_depIdxs = nil
}
