// Code generated by gowrap. DO NOT EDIT.
// template: ../../templates/log
// gowrap: http://github.com/hexdigest/gowrap

package grpc

import (
	"context"
	"log"

	payrollv1 "github.com/antosdaniel/go-presentation-generate-code/internal/grpc/payroll/v1"
	connect_go "github.com/bufbuild/connect-go"
)

// PayrollServiceServerWithLog implements PayrollServiceServer that is instrumented with logging
type PayrollServiceServerWithLog struct {
	_base PayrollServiceServer
}

// NewPayrollServiceServerWithLog instruments an implementation of the PayrollServiceServer with simple logging
func NewPayrollServiceServerWithLog(base PayrollServiceServer) PayrollServiceServerWithLog {
	return PayrollServiceServerWithLog{_base: base}
}

// AddPayroll implements PayrollServiceServer
func (_d PayrollServiceServerWithLog) AddPayroll(ctx context.Context, pp1 *connect_go.Request[payrollv1.AddPayrollRequest]) (pp2 *connect_go.Response[payrollv1.AddPayrollResponse], err error) {
	_params := []interface{}{"PayrollServiceServerWithLog: calling AddPayroll with params:", ctx, pp1}
	log.Println(_params...)
	defer func() {
		_results := []interface{}{"PayrollServiceServerWithLog: AddPayroll returned results:", pp2, err}
		if err != nil {
			log.Println(_results...)
		} else {
			log.Println(_results...)
		}
	}()
	return _d._base.AddPayroll(ctx, pp1)
}

// AddPayslip implements PayrollServiceServer
func (_d PayrollServiceServerWithLog) AddPayslip(ctx context.Context, pp1 *connect_go.Request[payrollv1.AddPayslipRequest]) (pp2 *connect_go.Response[payrollv1.AddPayslipResponse], err error) {
	_params := []interface{}{"PayrollServiceServerWithLog: calling AddPayslip with params:", ctx, pp1}
	log.Println(_params...)
	defer func() {
		_results := []interface{}{"PayrollServiceServerWithLog: AddPayslip returned results:", pp2, err}
		if err != nil {
			log.Println(_results...)
		} else {
			log.Println(_results...)
		}
	}()
	return _d._base.AddPayslip(ctx, pp1)
}

// GetPayroll implements PayrollServiceServer
func (_d PayrollServiceServerWithLog) GetPayroll(ctx context.Context, pp1 *connect_go.Request[payrollv1.GetPayrollRequest]) (pp2 *connect_go.Response[payrollv1.GetPayrollResponse], err error) {
	_params := []interface{}{"PayrollServiceServerWithLog: calling GetPayroll with params:", ctx, pp1}
	log.Println(_params...)
	defer func() {
		_results := []interface{}{"PayrollServiceServerWithLog: GetPayroll returned results:", pp2, err}
		if err != nil {
			log.Println(_results...)
		} else {
			log.Println(_results...)
		}
	}()
	return _d._base.GetPayroll(ctx, pp1)
}
