// Code generated by gowrap. DO NOT EDIT.
// template: ../../templates/log
// gowrap: http://github.com/hexdigest/gowrap

package grpc

import (
	context "context"
	"io"
	"log"

	v1 "github.com/antosdaniel/go-presentation-generate-code/gen/api/grpc/payroll/v1"
	"github.com/antosdaniel/go-presentation-generate-code/gen/api/grpc/payroll/v1/payrollv1connect"
	connect_go "github.com/bufbuild/connect-go"
)

// PayrollServiceHandlerWithLog implements payrollv1connect.PayrollServiceHandler that is instrumented with logging
type PayrollServiceHandlerWithLog struct {
	_stdlog, _errlog *log.Logger
	_base            payrollv1connect.PayrollServiceHandler
}

// NewPayrollServiceHandlerWithLog instruments an implementation of the payrollv1connect.PayrollServiceHandler with simple logging
func newPayrollServiceHandlerWithLog(base payrollv1connect.PayrollServiceHandler, stdout, stderr io.Writer) PayrollServiceHandlerWithLog {
	return PayrollServiceHandlerWithLog{
		_base:   base,
		_stdlog: log.New(stdout, "", log.LstdFlags),
		_errlog: log.New(stderr, "", log.LstdFlags),
	}
}

// AddPayroll implements payrollv1connect.PayrollServiceHandler
func (_d PayrollServiceHandlerWithLog) AddPayroll(ctx context.Context, pp1 *connect_go.Request[v1.AddPayrollRequest]) (pp2 *connect_go.Response[v1.AddPayrollResponse], err error) {
	_params := []interface{}{"PayrollServiceHandlerWithLog: calling AddPayroll with params:", ctx, pp1}
	_d._stdlog.Println(_params...)
	defer func() {
		_results := []interface{}{"PayrollServiceHandlerWithLog: AddPayroll returned results:", pp2, err}
		if err != nil {
			_d._errlog.Println(_results...)
		} else {
			_d._stdlog.Println(_results...)
		}
	}()
	return _d._base.AddPayroll(ctx, pp1)
}

// AddPayslip implements payrollv1connect.PayrollServiceHandler
func (_d PayrollServiceHandlerWithLog) AddPayslip(ctx context.Context, pp1 *connect_go.Request[v1.AddPayslipRequest]) (pp2 *connect_go.Response[v1.AddPayslipResponse], err error) {
	_params := []interface{}{"PayrollServiceHandlerWithLog: calling AddPayslip with params:", ctx, pp1}
	_d._stdlog.Println(_params...)
	defer func() {
		_results := []interface{}{"PayrollServiceHandlerWithLog: AddPayslip returned results:", pp2, err}
		if err != nil {
			_d._errlog.Println(_results...)
		} else {
			_d._stdlog.Println(_results...)
		}
	}()
	return _d._base.AddPayslip(ctx, pp1)
}

// GetPayroll implements payrollv1connect.PayrollServiceHandler
func (_d PayrollServiceHandlerWithLog) GetPayroll(ctx context.Context, pp1 *connect_go.Request[v1.GetPayrollRequest]) (pp2 *connect_go.Response[v1.GetPayrollResponse], err error) {
	_params := []interface{}{"PayrollServiceHandlerWithLog: calling GetPayroll with params:", ctx, pp1}
	_d._stdlog.Println(_params...)
	defer func() {
		_results := []interface{}{"PayrollServiceHandlerWithLog: GetPayroll returned results:", pp2, err}
		if err != nil {
			_d._errlog.Println(_results...)
		} else {
			_d._stdlog.Println(_results...)
		}
	}()
	return _d._base.GetPayroll(ctx, pp1)
}
